name: WOL Wonen
favicon: null
layout_spectrum: 0.8
typography_spectrum: 0.86486
title: Wol Wonen
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a0a0a0'
    - '#e4e4e4'
    - '#c2c2c2'
    - '#303030'
    - '#4e4e4e'
  brandStrength: 1
  lightness: 0.875
  saturation: 1
  rhythmicContrast: 0.5
purpose:
  - name: awareness
    item: null
    url: null
